Repository 93HSpring/CoffeeReview-v2, pull requests merged in 2020-12, with the labels that each got.

#94 feat: nav-bar 상단 탭 수정
  src/main/webapp/WEB-INF/views/includes/nav.jsp
  target/m2e-wtp/web-resources/META-INF/maven/com.coffeereview/controller/pom.properties
Labels: enhancement

#96 fix: 로그아웃할때 SQL Error 해결
  src/main/java/com/coffeereview/config/SecurityConfig.java
  src/main/java/com/coffeereview/security/CustomLoginSuccessHandler.java
Labels: fix

#97 feat: 메뉴 리스트 정렬 기능 추가
  src/main/resources/com/coffeereview/mapper/MenuMapper.xml
Labels: enhancement

#99 fix: 메뉴 리스트에 별점이 갱신 안되는 문제 해결
  src/main/java/com/coffeereview/controller/ReplyController.java
  src/main/java/com/coffeereview/domain/ReplyPageDTO.java
  src/main/java/com/coffeereview/service/ReplyService.java
  src/main/java/com/coffeereview/service/ReplyServiceImpl.java
Labels: fix

#100 fix: 리뷰 제거 문제 해결
  src/main/webapp/WEB-INF/views/menu/info.jsp
Labels: fix

#101 feat: logoutSuccessHandler 해결
  src/main/java/com/coffeereview/config/SecurityConfig.java
  src/main/java/com/coffeereview/security/CustomLogoutSuccessHandler.java
Labels: enhancement

#103 refactor: User관련 클래스 전면 수정을 위한 issue 삭제
  src/main/java/com/coffeereview/security/CustomUserDetailsService.java
  src/main/java/com/coffeereview/service/UserServiceImpl.java
  src/main/webapp/WEB-INF/views/includes/nav.jsp
  target/m2e-wtp/web-resources/META-INF/maven/com.coffeereview/controller/pom.properties
Labels: fix

#105 refactor: User** -> Member** 클래스명 변경
  src/main/java/com/coffeereview/controller/MemberController.java
  src/main/java/com/coffeereview/domain/MemberVO.java
  src/main/java/com/coffeereview/mapper/MemberMapper.java
  src/main/java/com/coffeereview/security/CustomUserDetailsService.java
  src/main/java/com/coffeereview/security/domain/CustomUser.java
  src/main/java/com/coffeereview/service/MemberService.java
  src/main/java/com/coffeereview/service/MemberServiceImpl.java
  src/main/resources/com/coffeereview/mapper/MemberMapper.xml
  src/test/java/com/coffeereview/mapper/MemberMapperTests.java
Labels: fix

#107 refactor: user** -> member** 테이블명 변경
  src/main/java/com/coffeereview/controller/MemberController.java
  src/main/java/com/coffeereview/domain/MemberVO.java
  src/main/resources/com/coffeereview/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/user/register.jsp
Labels: fix

#109 refactor: 기존의 MemberService 삭제
  src/main/java/com/coffeereview/config/SecurityConfig.java
  src/main/java/com/coffeereview/security/MemberService.java
  src/main/resources/com/coffeereview/mapper/MemberMapper.xml
Labels: fix

#110 feat: 메뉴 성분별 정렬 기능 추가
  src/main/java/com/coffeereview/domain/Criteria.java
  src/main/resources/com/coffeereview/mapper/MenuMapper.xml
  src/main/resources/log4j.xml
  src/main/webapp/WEB-INF/views/menu/info.jsp
  src/main/webapp/WEB-INF/views/menu/list.jsp
  src/test/java/com/coffeereview/mapper/MenuMapperTests.java
  target/classes/log4j.xml
Labels: enhancement

#114 fix: 서버 오류 해결
  src/main/java/com/coffeereview/config/SecurityConfig.java
  src/main/java/com/coffeereview/controller/MemberController.java
  src/main/webapp/WEB-INF/views/includes/nav.jsp
  src/main/webapp/WEB-INF/views/member/index.jsp
  src/main/webapp/WEB-INF/views/member/login.jsp
  src/main/webapp/WEB-INF/views/member/register.jsp
  src/main/webapp/WEB-INF/views/member/user_index.jsp
  target/m2e-wtp/web-resources/META-INF/maven/com.coffeereview/controller/pom.properties
Labels: fix

#116 refactoring: MenuController REST 방식으로 변환
  src/main/java/com/coffeereview/controller/MenuController.java
  src/test/java/com/coffeereview/controller/MenuControllerTests.java
  target/m2e-wtp/web-resources/META-INF/maven/com.coffeereview/controller/pom.properties
Labels: refactoring

#118 feature: Password Encoding을 포함한 회원가입 구현
  src/main/java/com/coffeereview/controller/MemberController.java
  src/main/java/com/coffeereview/security/MemberService.java
  src/main/java/com/coffeereview/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/views/member/register.jsp
Labels: enhancement
